import { Card, CardUpdate } from '@/lib/types/card';

const DIMENSIONS = ['who', 'what', 'when', 'where'] as const;

const EXCERPT_MAX_LENGTH = 150;

/**
 * Quote card attribution for feed/detail: prefer `subtitle`, else `excerpt`.
 * Prefixes an em dash when the string does not already start with a dash character.
 */
export function formatQuoteAttribution(
  subtitle: string | null | undefined,
  excerpt: string | null | undefined
): string {
  const raw = subtitle?.trim() || excerpt?.trim() || '';
  if (!raw) return '';
  if (/^[\u2014\u2013\u2012\u2015\-–—]\s*/.test(raw)) return raw;
  return `\u2014 ${raw}`;
}

/** Strips HTML tags and entities, returning plain text. */
export function stripHtml(html: string): string {
  return html
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

/** Generates an excerpt from HTML content by stripping tags and truncating at a word boundary. */
export function generateExcerpt(html: string | null | undefined, maxLength = EXCERPT_MAX_LENGTH): string {
  if (!html) return '';
  const plain = stripHtml(html);
  if (plain.length <= maxLength) return plain;
  const truncated = plain.slice(0, maxLength);
  const lastSpace = truncated.lastIndexOf(' ');
  return (lastSpace > maxLength * 0.6 ? truncated.slice(0, lastSpace) : truncated) + '…';
}

/**
 * Groups collection cards by dimension (who, what, when, where).
 * A collection appears in every dimension group it has tags for (Option B).
 * Uncategorized: collections with no tags in any dimension.
 * Within each group, sorted by title A-Z.
 */
export function groupCollectionsByDimension(cards: Card[]): Record<string, Card[]> {
  const groups: Record<string, Card[]> = {
    who: [],
    what: [],
    when: [],
    where: [],
    uncategorized: [],
  };

  for (const card of cards) {
    const hasAnyTag =
      (card.who?.length ?? 0) > 0 ||
      (card.what?.length ?? 0) > 0 ||
      (card.when?.length ?? 0) > 0 ||
      (card.where?.length ?? 0) > 0;

    if (!hasAnyTag) {
      groups.uncategorized.push(card);
      continue;
    }

    for (const dim of DIMENSIONS) {
      const tags = card[dim];
      if (tags && tags.length > 0) {
        groups[dim].push(card);
      }
    }
  }

  // Sort each group by title A-Z
  for (const key of Object.keys(groups)) {
    groups[key].sort((a, b) => {
      const titleA = (a.title || a.subtitle || 'Untitled').toLowerCase();
      const titleB = (b.title || b.subtitle || 'Untitled').toLowerCase();
      return titleA.localeCompare(titleB);
    });
  }

  return groups;
}
import { Media } from '@/lib/types/photo';
import { Node } from 'prosemirror-model';
import { Editor } from '@tiptap/react';

/**
 * Extracts media IDs from the HTML string saved in a card's `content` field.
 * We look for any <figure data-media-id="…"> generated by TipTap's FigureWithImage node.
 */
export function extractMediaFromContent(html: string | null | undefined): string[] {
  if (!html || typeof html !== 'string') return [];

  const ids = new Set<string>();
  const regex = /<figure[^>]*data-media-id=["']([^"']+)["']/gi;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(html)) !== null) {
    ids.add(match[1]);
  }
  return Array.from(ids);
}

/** Removes the <figure> element for the given mediaId from content HTML. */
export function removeMediaFromContent(html: string | null | undefined, mediaId: string): string {
  if (!html || typeof html !== 'string') return html || '';
  const escaped = mediaId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return html.replace(
    new RegExp(
      `<figure[^>]*data-media-id=["']${escaped}["'][^>]*>[\\s\\S]*?<\\/figure>`,
      'gi'
    ),
    ''
  ).replace(/\n\s*\n\s*\n/g, '\n\n');
}

export function transformToCardUpdate(hydratedCard: Card): CardUpdate {
  const skinnyGalleryMedia = (hydratedCard.galleryMedia ?? []).map(item => {
    const trimmed = item.objectPosition?.trim();
    return {
      mediaId: item.mediaId,
      order: item.order,
      ...(Object.prototype.hasOwnProperty.call(item, 'caption')
        ? { caption: item.caption ?? '' }
        : {}),
      ...(trimmed ? { objectPosition: trimmed } : {}),
    };
  });

  const contentMedia = extractMediaFromContent(hydratedCard.content);

  return {
    title: hydratedCard.title,
    status: hydratedCard.status,
    content: hydratedCard.content,
    tags: hydratedCard.tags,
    childrenIds: hydratedCard.childrenIds,
    coverImageId: hydratedCard.coverImageId,
    coverImageFocalPoint: hydratedCard.coverImageFocalPoint,
    galleryMedia: skinnyGalleryMedia,
    contentMedia,
  };
}

/**
 * Removes transient fields (coverImage, galleryMedia[].media, contentMedia objects) so the
 * resulting payload matches the Firestore card schema.
 */
export function dehydrateCardForSave(raw: any): CardUpdate {
  const { 
    coverImage: _ci, 
    galleryMedia, 
    contentMedia, 
    // Server-generated fields to exclude
    docId,
    title_lowercase,
    createdAt,
    updatedAt,
    filterTags,
    who,
    what,
    when,
    where,
    // Legacy fields to exclude
    inheritedTags,
    tagPathsMap,
    ...rest 
  } = raw;

  // Coerce to array so "missing gallery" and "empty gallery" match for dirty/compare and PATCH slices.
  const gallerySource = Array.isArray(galleryMedia) ? galleryMedia : [];
  const dehydratedGallery = gallerySource.map((item: any) => {
    const { media: _m, ...g } = item || {};
    let out = { ...g };
    const trimmed = typeof out.objectPosition === 'string' ? out.objectPosition.trim() : '';
    if (!trimmed) {
      const { objectPosition: _op, ...rest } = out;
      out = rest;
    } else {
      out = { ...out, objectPosition: trimmed };
    }
    if (!Object.prototype.hasOwnProperty.call(out, 'caption') || out.caption === undefined) {
      const { caption: _c, ...rest } = out;
      out = rest;
    }
    return out;
  });

  // Ensure contentMedia is always an array before saving.
  const cleanedContent = Array.isArray(contentMedia) ? contentMedia : [];

  const result = {
    ...rest,
    content: raw.content, // Explicitly preserve content
    // Always include coverImageId so removals persist. null = clear, omit would mean "don't change"
    coverImageId: raw.coverImageId ?? null,
    // Always include tags/children/gallery/contentMedia when present (including empty arrays) so removals persist
    ...(Array.isArray(raw.tags) ? { tags: raw.tags } : {}),
    ...(Array.isArray(raw.childrenIds) ? { childrenIds: raw.childrenIds } : {}),
    galleryMedia: dehydratedGallery,
    ...(Array.isArray(cleanedContent) ? { contentMedia: cleanedContent } : {}),
  } as CardUpdate;

  return result;
}

/** Recursively sort object keys so JSON.stringify is stable for comparison. */
function sortKeysDeep(value: unknown): unknown {
  if (value === null || typeof value !== 'object') {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(sortKeysDeep);
  }
  const obj = value as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(obj).sort()) {
    out[k] = sortKeysDeep(obj[k]);
  }
  return out;
}

/**
 * Normalize body HTML so TipTap re-serialization vs Firestore/hydrated markup does not
 * falsely mark the form dirty (src URLs stripped server-side; whitespace/NBSP differences).
 */
export function normalizeHtmlForDirtyCompare(html: string | null | undefined): string {
  if (!html || typeof html !== 'string') return '';
  const stripped = stripContentImageSrc(html);
  return stripped
    .replace(/\u00a0/g, ' ')
    .replace(/>\s+</g, '><')
    .trim();
}

function prepareCardUpdateForDirtyCompare(c: CardUpdate): CardUpdate {
  const next: CardUpdate = { ...c };
  if (typeof next.content === 'string') {
    const norm = normalizeHtmlForDirtyCompare(next.content);
    next.content = norm;
    next.contentMedia = extractMediaFromContent(norm);
  }
  return next;
}

/** Denormalized / server-maintained — must not drive leave-confirm false positives. */
const DERIVED_CARD_KEYS_FOR_DIRTY = new Set([
  'curatedNavEligible',
  'journalWhenSortAsc',
  'journalWhenSortDesc',
]);

function omitDerivedCardFieldsForDirtyCompare(value: unknown): unknown {
  if (value === null || typeof value !== 'object') {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(omitDerivedCardFieldsForDirtyCompare);
  }
  const o = value as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(o).sort()) {
    if (DERIVED_CARD_KEYS_FOR_DIRTY.has(k)) continue;
    out[k] = omitDerivedCardFieldsForDirtyCompare(o[k]);
  }
  return out;
}

/**
 * True if two card states would persist the same payload (after dehydrate).
 * Ignores transient/hydrated fields (cover object, gallery media blobs, etc.).
 */
export function persistableSnapshotsEqual(a: CardUpdate, b: CardUpdate): boolean {
  const da = omitDerivedCardFieldsForDirtyCompare(
    sortKeysDeep(dehydrateCardForSave(prepareCardUpdateForDirtyCompare(a)))
  );
  const db = omitDerivedCardFieldsForDirtyCompare(
    sortKeysDeep(dehydrateCardForSave(prepareCardUpdateForDirtyCompare(b)))
  );
  return JSON.stringify(da) === JSON.stringify(db);
}

/**
 * Ensures that each <figure> in the HTML content points at the canonical `storageUrl` of its media.
 * This replaces any temporary or proxy URL that may have been inserted during editing.
 */
export function normalizeContentImageSrc(html: string, mediaMap: Map<string, Media>): string {
  if (!html) return html;
  let updated = html;
  for (const [id, media] of mediaMap.entries()) {
    if (!media?.storageUrl) continue;

    const tagRegex = new RegExp(
      `<(figure|img)([^>]*?data-media-id=["']${id}["'][^>]*?)>`,
      'gi'
    );

    updated = updated.replace(tagRegex, (tag, tagName, attrs) => {
      if (/src=/.test(tag)) {
        return tag.replace(/src=["'][^"']*["']/, `src="${media.storageUrl}"`);
      }
      return tag.replace(`<${tagName}`, `<${tagName} src="${media.storageUrl}"`);
    });
  }
  return updated;
}

export function stripContentImageSrc(html: string | null | undefined): string {
  if (!html || typeof html !== 'string') {
    return html || '';
  }

  // First handle standalone img tags
  let result = html.replace(/<img[^>]*data-media-id=["'][^"']+["'][^>]*>/gi, (tag) => {
    // Remove the src="..." portion if it exists
    return tag.replace(/\s+src=["'][^"']*["']/i, '');
  });

  // Then handle figure tags with nested img tags
  result = result.replace(
    /<figure[^>]*data-media-id=["'][^"']+["'][^>]*>(\s*<img[^>]*>.*?)<\/figure>/gi,
    (match, imgContent) => {
      // Keep the figure tag intact but strip src from the nested img
      const cleanedImgContent = imgContent.replace(/\s+src=["'][^"']*["']/i, '');
      return match.replace(imgContent, cleanedImgContent);
    }
  );

  return result;
}

/**
 * Injects the permanent storageUrl for each mediaId into its corresponding <img> tag.
 * If the tag already contains a src attribute it will be overwritten; otherwise it is added.
 */
export function hydrateContentImageSrc(html: string | null | undefined, mediaMap: Map<string, Media>): string {
  if (!html || typeof html !== 'string') {
    return html || '';
  }

  // First handle standalone img tags
  let result = html.replace(/<img[^>]*data-media-id=["']([^"']+)["'][^>]*>/gi, (tag, mediaId: string) => {
    const media = mediaMap.get(mediaId);
    if (!media || !media.storageUrl) {
      return tag;
    }

    // If a src attribute already exists, replace its value; otherwise insert it after <img
    if (/src=["'][^"']*["']/i.test(tag)) {
      return tag.replace(/src=["'][^"']*["']/i, `src="${media.storageUrl}"`);
    }
    return tag.replace(/^<img/i, `<img src="${media.storageUrl}"`);
  });

  // Then handle figure tags with nested img tags
  result = result.replace(
    /<figure[^>]*data-media-id=["']([^"']+)["'][^>]*>(\s*<img[^>]*>.*?)<\/figure>/gi,
    (match, mediaId: string, imgContent: string) => {
      const media = mediaMap.get(mediaId);
      if (!media || !media.storageUrl) {
        return match;
      }

      // Update or add src to the nested img tag
      const updatedImgContent = imgContent.replace(/<img([^>]*)>/i, (imgTag) => {
        if (/src=["'][^"']*["']/i.test(imgTag)) {
          return imgTag.replace(/src=["'][^"']*["']/i, `src="${media.storageUrl}"`);
        }
        return imgTag.replace(/^<img/i, `<img src="${media.storageUrl}"`);
      });

      return match.replace(imgContent, updatedImgContent);
    }
  );

  return result;
} 